version: 0.2

secrets-manage:
  username: MongoDB:username
  password: MongoDB:password

phases:
  pre_build:
    commands:
      - echo username
      - echo "Pre-build phase"
  
  build:
    commands:
      - echo "Build phase"
  
  post_build:
    commands:
      - echo "All good"


