version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - printenv
  
  build:
    commands:
      - echo "Build phase"
      - npm build
     
  
  post_build:
    commands:
      - echo "All good"


   


